/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py on 2023-11-26

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/

#ifndef EF_PWM32_REGS_H
#define EF_PWM32_REGS_H

#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define EF_PWM32_CLKDIV_REG_CLKDIV		0
#define EF_PWM32_CLKDIV_REG_CLKDIV_LEN	4
#define EF_PWM32_CONTROL_REG_EN		0
#define EF_PWM32_CONTROL_REG_EN_LEN	1
#define EF_PWM32_CONTROL_REG_PWMA_EN		1
#define EF_PWM32_CONTROL_REG_PWMA_EN_LEN	1
#define EF_PWM32_CONTROL_REG_PWMB_EN		2
#define EF_PWM32_CONTROL_REG_PWMB_EN_LEN	1
#define EF_PWM32_CONTROL_REG_PWMA_INV		3
#define EF_PWM32_CONTROL_REG_PWMA_INV_LEN	1
#define EF_PWM32_CONTROL_REG_PWMBINV		4
#define EF_PWM32_CONTROL_REG_PWMBINV_LEN	1
#define EF_PWM32_CONTROL_REG_CNTR_MODE		5
#define EF_PWM32_CONTROL_REG_CNTR_MODE_LEN	1
#define EF_PWM32_GENA_REG_ZERO		0
#define EF_PWM32_GENA_REG_ZERO_LEN	2
#define EF_PWM32_GENA_REG_AUP		2
#define EF_PWM32_GENA_REG_AUP_LEN	2
#define EF_PWM32_GENA_REG_BUP		4
#define EF_PWM32_GENA_REG_BUP_LEN	2
#define EF_PWM32_GENA_REG_TOP		6
#define EF_PWM32_GENA_REG_TOP_LEN	2
#define EF_PWM32_GENA_REG_BD		8
#define EF_PWM32_GENA_REG_BD_LEN	2
#define EF_PWM32_GENA_REG_AD		10
#define EF_PWM32_GENA_REG_AD_LEN	2
#define EF_PWM32_GENB_REG_ZERO		0
#define EF_PWM32_GENB_REG_ZERO_LEN	2
#define EF_PWM32_GENB_REG_AUP		2
#define EF_PWM32_GENB_REG_AUP_LEN	2
#define EF_PWM32_GENB_REG_BUP		4
#define EF_PWM32_GENB_REG_BUP_LEN	2
#define EF_PWM32_GENB_REG_TOP		6
#define EF_PWM32_GENB_REG_TOP_LEN	2
#define EF_PWM32_GENB_REG_BD		8
#define EF_PWM32_GENB_REG_BD_LEN	2
#define EF_PWM32_GENB_REG_AD		10
#define EF_PWM32_GENB_REG_AD_LEN	2

typedef struct _EF_PWM32_TYPE_ {
	__RW	cmpA;
	__RW	cmpB;
	__RW	top;
	__RW	clkdiv;
	__RW	control;
	__RW	GENA;
	__RW	GENB;
	__R 	reserved[953];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} EF_PWM32_TYPE;

#endif