SIM-RTL:
	iverilog EF_PWM32_apb_tb.v ../../hdl/rtl/EF_PWM32.v ../../hdl/rtl/bus_wrappers/EF_PWM32_apb.v
	./a.out

SIM-GL:
	iverilog EF_PWM32_apb_tb.v ../../hdl/rtl/EF_PWM32.v ../../hdl/gl/sky130/EF_PWM32_apb.v ../../util/tech/sky130/sky130_hd.v
	./a.out
